#pragma once
#include "order.hpp"
#include <map>
#include <unordered_map>
#include <vector>
#include <functional>

// ---------------------------------------------------------------------------
// Trade  —  produced whenever two orders cross
// ---------------------------------------------------------------------------
struct Trade {
    OrderId  buy_order_id;
    OrderId  sell_order_id;
    Price    price;
    Quantity quantity;
};

// One price level = a queue of resting orders at the same price (FIFO)
using PriceLevel = std::vector<Order>;

// ---------------------------------------------------------------------------
// OrderBook  —  Phase 1 STL baseline
//
// Data structures:
//   bids_ : std::map<Price, PriceLevel, std::greater<Price>>
//           highest bid at begin()  →  O(log P) insert, O(1) best-bid access
//   asks_ : std::map<Price, PriceLevel>
//           lowest ask at begin()   →  O(log P) insert, O(1) best-ask access
//   order_index_ : unordered_map<OrderId, {Side, Price}>
//           O(1) average cancel lookup
//
// vs your original baseline:
//   old: std::vector + std::sort on every insert  →  O(N log N) per add
//   old: linear scan for cancel                   →  O(N) per cancel
//   new: std::map maintains order automatically   →  O(log P) per add
//   new: hash map for cancel                      →  O(1) per cancel
// ---------------------------------------------------------------------------
class OrderBook {
public:
    // Returns all trades generated by this order (empty if nothing matched)
    std::vector<Trade> add_order(Order order);

    // Returns true if the order was found and removed
    bool cancel_order(OrderId id);

    // Pretty-print the top `depth` levels on each side
    void print_book(int depth = 5) const;

private:
    std::map<Price, PriceLevel, std::greater<Price>> bids_; // best bid first
    std::map<Price, PriceLevel>                      asks_; // best ask first
    std::unordered_map<OrderId, std::pair<Side, Price>> order_index_;

    // Core matching logic — modifies incoming in place, returns trades
    std::vector<Trade> match(Order& incoming);
};